import sublime

__all__ = ('LANGUAGES',)

Item = lambda trigger, *args: sublime.CompletionItem(trigger, kind=sublime.KIND_NAMESPACE, *args)

# See https://l10n.kde.org/teams-list.php
LANGUAGES = (
    Item("ar",          "Arabic"),
    Item("as",          "Assamese"),
    Item("ast",         "Asturian"),
    Item("az",          "Azerbaijani"),
    Item("bg",          "Bulgarian"),
    Item("bn",          "Bengali"),
    Item("bs",          "Bosnian"),
    Item("ca",          "Catalan"),
    Item("ca@valencia", "Catalan (Valencian)"),
    Item("cs",          "Czech"),
    Item("da",          "Danish"),
    Item("de",          "German"),
    Item("el",          "Greek"),
    Item("en_GB",       "British English"),
    Item("eo",          "Esperanto"),
    Item("es",          "Spanish"),
    Item("et",          "Estonian"),
    Item("eu",          "Basque"),
    Item("fa",          "Persian"),
    Item("fi",          "Finnish"),
    Item("fr",          "French"),
    Item("fy",          "Frisian"),
    Item("ga",          "Irish"),
    Item("gd",          "Scottish Gaelic"),
    Item("gl",          "Galician"),
    Item("gu",          "Gujarati"),
    Item("he",          "Hebrew"),
    Item("hi",          "Hindi (हिन्दी)"),
    Item("hr",          "Croatian [Hrvatski]"),
    Item("hu",          "Hungarian"),
    Item("ia",          "Interlingua"),
    Item("id",          "Indonesian"),
    Item("ie",          "Interlingue"),
    Item("is",          "Icelandic"),
    Item("it",          "Italian"),
    Item("ja",          "Japanese"),
    Item("kk",          "Kazakh"),
    Item("km",          "Khmer"),
    Item("kn",          "Kannada"),
    Item("ko",          "Korean (한국어)"),
    Item("lt",          "Lithuanian"),
    Item("lv",          "Latvian"),
    Item("mai",         "Maithili"),
    Item("mk",          "Macedonian"),
    Item("ml",          "Malayalam | മലയാളം"),
    Item("mr",          "Marathi"),
    Item("ms",          "Malay"),
    Item("my",          "Burmese"),
    Item("nb",          "Norwegian Bokmål"),
    Item("nl",          "Dutch"),
    Item("nn",          "Norwegian Nynorsk"),
    Item("oc",          "Occitan"),
    Item("pa",          "Punjabi"),
    Item("pl",          "Polish"),
    Item("pt",          "Portuguese"),
    Item("pt_BR",       "Brazilian Portuguese"),
    Item("ro",          "Romanian"),
    Item("ru",          "Russian"),
    Item("se",          "Northern Sami"),
    Item("si",          "Sinhala"),
    Item("sk",          "Slovak"),
    Item("sl",          "Slovenian"),
    Item("sq",          "Albanian"),
    Item("sr",          "Serbian"),
    Item("sv",          "Swedish"),
    Item("ta",          "Tamil"),
    Item("te",          "Telugu"),
    Item("tg",          "Tajik"),
    Item("th",          "Thai"),
    Item("tok",         "Toki Pona"),
    Item("tr",          "Turkish"),
    Item("tt",          "Tatar"),
    Item("ug",          "Uyghur"),
    Item("uk",          "Ukrainian"),
    Item("vi",          "Vietnamese"),
    Item("wa",          "Walloon"),
    Item("zh_CN",       "Chinese Simplified"),
    Item("zh_TW",       "Chinese Traditional"),
)
